- hosts: localhost
  connection: local

  vars:
    password: rstudio

  tasks:
      
    -   name: Check the version of OS
        command: hostnamectl
        register: os_check
        ignore_errors: yes 

    -   name: Add an apt key - Ubuntu 
        shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
        when:
            - os_check.stdout | regex_search("Ubuntu")

    -   name: Add an apt repo - Ubuntu 18
        shell: add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/'
        when:
            - os_check.stdout | regex_search("Ubuntu 18")

    -   name: Add an apt repo - Ubuntu 20
        shell: add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
        when:
            - os_check.stdout | regex_search("Ubuntu 20")

    -   name: Install R - Ubuntu
        apt: name={{ item }} update_cache=yes state=present
        loop: [ 'r-base', 'libapparmor1', 'gdebi-core' ]
        when:
            - os_check.stdout | regex_search("Ubuntu")

    -   name: Add RStudio - Ubuntu
        get_url:
            url: https://download2.rstudio.org/server/bionic/amd64/rstudio-server-1.3.1056-amd64.deb
            dest: /tmp/rstudio-server-1.3.1056-amd64.deb
        when:
            - os_check.stdout | regex_search("Ubuntu")

    -   name: Install RStudio
        shell: gdebi /tmp/rstudio-server-1.3.1056-amd64.deb -n
        when:
            - os_check.stdout | regex_search("Ubuntu")

    -   name: install Epel Release
        yum:
            name: epel-release
            state: latest
        when:
            - os_check.stdout | regex_search("CentOS")

    -   name: upgrade all packages
        yum:
            name: '*'
            state: latest
        when:
            - os_check.stdout | regex_search("CentOS")

    -   name: Enable Power Tools - centOS 8
        shell: dnf config-manager --set-enabled PowerTools
        when: 
            - os_check.stdout | regex_search("CentOS Linux 8")

    -   name: install R
        yum:
            name: R
            state: present
        when:
            - os_check.stdout | regex_search("CentOS")


    -   name: Add RStudio - CentOS 7
        get_url:
            url: https://download2.rstudio.org/server/centos6/x86_64/rstudio-server-rhel-1.3.1056-x86_64.rpm
            dest: /tmp/rstudio-server-rhel-1.3.1056-x86_64.rpm
        when:
            - os_check.stdout | regex_search("CentOS Linux 7")


    -   name: Add RStudio - CentOS 8
        get_url:
            url: https://download2.rstudio.org/server/centos8/x86_64/rstudio-server-rhel-1.3.1056-x86_64.rpm
            dest: /tmp/rstudio-server-rhel-1.3.1056-x86_64.rpm
        when:
            - os_check.stdout | regex_search("CentOS Linux 8")

    -   name: Install RStudio
        yum:
            name: /tmp/rstudio-server-rhel-1.3.1056-x86_64.rpm
            state: present
        when:
            - os_check.stdout | regex_search("CentOS")

    -   name: Add the user 'rstudio' 
        user:
            name: rstudio
            state: present
            password: "{{ password | password_hash('sha512') }}"

    -   name: Disable SELinux
        selinux:
            state: disabled
        when:
            - os_check.stdout | regex_search("CentOS Linux 8")